#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 21 11:56:12 +0330 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_cache_behav -key {Behavioral:sim_2:Functional:tb_cache} -tclbatch tb_cache.tcl -view /mnt/data/mnt_data/FPGA_Projects/Vivado/project_8_final/tb_cache_behav.wcfg -log simulate.log"
xsim tb_cache_behav -key {Behavioral:sim_2:Functional:tb_cache} -tclbatch tb_cache.tcl -view /mnt/data/mnt_data/FPGA_Projects/Vivado/project_8_final/tb_cache_behav.wcfg -log simulate.log

